import customtkinter as ctk


class CommonButton(ctk.CTkButton):
    def __init__(
        self,
        master,
        width=100,
        height=28,
        corner_radius=16,
        border_width=None,
        border_spacing=2,
        bg_color="transparent",
        fg_color=None,
        hover_color=None,
        border_color=None,
        text_color=None,
        text_color_disabled=None,
        background_corner_colors=None,
        round_width_to_even_numbers=True,
        round_height_to_even_numbers=True,
        text="Common Button",
        font=("Times New Roman", 16),
        textvariable=None,
        image=None,
        state="normal",
        hover=True,
        command=None,
        compound="left",
        anchor="center",
    ):
        super().__init__(
            master,
            width,
            height,
            corner_radius,
            border_width,
            border_spacing,
            bg_color,
            fg_color,
            hover_color,
            border_color,
            text_color,
            text_color_disabled,
            background_corner_colors,
            round_width_to_even_numbers,
            round_height_to_even_numbers,
            text=text,
            font=font,
            textvariable=textvariable,
            image=image,
            state=state,
            hover=hover,
            command=command,
            compound=compound,
            anchor=anchor,
        )
